import React from 'react'
import { Row, Col, Card, CardBody } from 'reactstrap'

const PrivacyPolicy = () => {
    return (
        <>
            <Row className='content-title pt-75'>
                <Col className='text-center privacy' sm='12'>
                    <h1 className='text-white'>Privacy Policy</h1>
                </Col>
                <Col sm='12'>
                    <Card className='text-justify bg-light-secondary privacy shadow-none py-1'>
                        <CardBody>
                            <p>Effective September 1, 2022</p>
                            <p className='font-weight'>A. About Us.</p>
                            <p>Welcome to Gameofgames.com (the “Website” or “Site”) and our Game of Games (the “Mobile Application”, “Mobile App”, or “App”) is owned and operated by Game of Games (the “Company”, “us”, “we”, or “our”).  The Site is a platform that provides data points and other analytics for related to sports, sports events, and sports contests. We do this through the services offered on the Website, Mobile Application and by the products and services otherwise offered by us (together with the Website, Mobile Application, Content (defined below), and all of the products and services offered by us, our “Services”). By accessing or using our Services, expressly agree to the provisions of and the data practices reflected in this Privacy Policy (our “Policy”), our Terms of Service, and any other policy we may develop from time to time (collectively, “Policies”), which create legal and enforceable agreements. If you do not agree to the practices described below in this Policy, do not browse our Website or use our Services, as your continued use of our Services indicates that you are agreeing to the collection, use, disclosure, management and storage of your Personal Data and other information as described in this Policy.</p>
                            <p className='font-weight'>B. Privacy Policy:</p>
                            <p>Please read this Policy as it includes important information regarding your Personal Data and other information. Capitalized terms not defined in this Policy will have the meanings given to such terms in the Terms of Service. As described in this privacy statement, we will not process your information without a lawful basis to do so.  We will process your user information with your legal consent (when you voluntarily provide information or opt in) or based on contract law (when you enter a transaction with us), or when we have a legal obligation to do so.  As described herein, we may also process certain user information on the basis of the following legitimate interests, provided that such interests are not overridden by your privacy rights and interests: delivering content, and further developments and improvements to the Site, learning from analyzing traffic to better serve all Site users, to analyze the likes and dislikes of our users, and to help us to provide a more stable, consistent, and secure user experience.  If you have any questions regarding this, please contact us.</p>
                            <p className='font-weight'>1. Information We Collect.</p>
                            <p>(a) Personal Data. Personal Data and other information are collected from you when you create a Profile with us or when you otherwise disclose Personal Data or other information to us or third parties when using the Services. “Personal Data” means any information that may be used to identify an individual. Personal Data does not include aggregate information. In connection with the Services, you may be asked to provide us the following Personal Data and other information: your name, email address, age, relevant preferences for the Site and Services, payment information, and other information in connection with the Services.</p>
                            <p>(b) Location Data. We and third parties with whom we may partner may collect location information in relation to a User’s Device and use of the Services (“Location Data”) with respect to you. If you use the Services, then you are providing consent to collect Location Data such as the physical location of your Device which will be used to provide you with certain features of the Services. This Location Data is collected anonymously in a form that does not personally identify you. Location Data is aggregated with data from Devices of other Users to enhance the quality of Content Users provide to us and to enhance the quality of the Services we provide to you. We may also share your Location data with third parties. Location Data is shared anonymously in a form that would not personally identify you.</p>
                            <p>(c) Use Data. When you send or receive Content using our Services, we collect data about that Content.</p>
                            <p>(d) Log Information. When you browse our Services, you do so anonymously, unless you have previously created a Profile with us. However, we may log your IP address to give us an idea of which part of our Services you visit and how long you spend there. However, we do not link your IP address to any Personal Data unless you have logged into our Services. Also, our Services may use a standard technology called a ‘cookie’ to collect information about how you interact with our Services. Please see Section 7 below for more information.</p>
                            <p>(e) Aggregate Data. Certain aspects of our Services are set up to collect and report aggregate information. Aggregate information is data we collect about the use of the Services or about a group or category of products, services or Users, from which individual identities or other Personal Data has been removed. In other words, information about how you use the Services may be collected and combined with information about how others use the Services. Aggregate data helps us understand trends and User’s needs so that we can better consider new features or otherwise tailor our Services. This Policy does not restrict what we can do with aggregate information.</p>
                            <p>(f) Analytics. We may use third-party analytics tools to collect information about use of our Services. Analytics tools collect information such as how often Users visit our Website, what pages Users visit when Users visit our Website, and the other websites they accessed prior to accessing our Website. We use the information we gather from analytics to improve our Services. Analytics tools collect information such as the IP address assigned to you on the date you visit our Website, but does not collect Personal Data. We do not combine the information collected through the use of analytics with Personal Data. Although our analytics tools may plant a cookie on your web browser to identify you as a unique User the next time you visit our Website, the cookie cannot be used by anyone but our analytics tools. In the event that we use Google’s ‘Google Analytics’, then Google’s ability to use and share information collected by ‘Google Analytics’ about your visits to our Website is restricted by the <a href="https://www.google.com/analytics/terms/" target='_blank'>Google Analytics Terms of Use</a> and the <a href="https://policies.google.com/privacy" target='_blank'>Google Privacy Policy</a>. You can prevent analytics tools from recognizing you on return visits to this Website by disabling cookies on web browser. See Section 7 below for more information.</p>
                            <p>(g) Device Information. We may collect data about the computer or Device you use to access our Services, including the hardware model, operating system and version, MAC address, unique device identifier (‘UDI’), phone number, and mobile carrier information.</p>
                            <p>(h) Tracking Technologies. We collect information through technology, such as cookies, flash cookies and web beacons, including when you visit our Services or Linked Sites. Please see Section 7 below for further information regarding tracking technologies.</p>
                            <p>(i) From Third Parties. We acquire information from other trusted sources to update or supplement the information you provided, or we collected automatically. Local law may require that you authorize the third-party to share your information with us before we can acquire it.</p>
                            <p><span className='font-weight'>2. How We Use It.</span> We use, allow access to, or disclose your Personal Data to third parties with whom we partner to:</p>
                            <p>(a) enable us to provide the Services to you;</p>
                            <p>(b) notify you regarding Services, your Profile, or fees;</p>
                            <p>(c) increase the usability of the Services;</p>
                            <p>(d) provide information about promotional offers;</p>
                            <p>(e) investigate objectionable use of the Services;</p>
                            <p>(f) respond to requests for assistance from our customer support team;</p>
                            <p>(g) deliver advertisements on our Services and on the websites of advertising partners, to improve and monitor advertising, and to provide you with targeted advertisements;</p>
                            <p>(h) analyze trends and use of our Services; and</p>
                            <p>(i) carry on our business, as determined by us.</p>
                            <p className='font-weight'>3. Who We Share It With.</p>
                            <p>We will share your Personal Data with third parties:</p>
                            <p>(a) When you have enabled us to share your Personal Data with another company or our Affiliates, such as: in sending you offers and promotions about their products and services; or allowing us to share your personal data with third parties or Linked Sites, such as Social Media Profiles. Once we share your Personal Data with another company, the information received by the other company becomes subject to the other company’s privacy practices.</p>
                            <p>(b) When necessary, as determined by us in our sole discretion, to provide Services to you. This includes for the uses listed in Section 2 above.</p>
                            <p>(c) When required by law or by court order.</p>
                            <p>(d) To protect our rights and property, to prevent fraudulent activity or other deceptive practices of Users or third parties, or to prevent harm to others.</p>
                            <p>(e) If we are acquired by or merged with another company, or if our assets are sold to another company. In all of these circumstances, you understand and agree that our Terms of Service and this Policy will be assigned and delegated to the other company.</p>
                            <p>(f) To perform tasks for us or in connection with our business, as determined by us. We may use third parties to help operate the Services and perform other aspects of the Services. You agree we may share your Personal Data with our Affiliates and other third parties that provide services to us in connection with our business (such as our payment processor, website or database hosting companies, address list hosting companies, email service providers, analytics companies, distribution companies, and other similar service providers that use such information on our behalf). Unless otherwise stated, these third parties do not have any right to use the Personal Data we provide to them beyond what is necessary for them to assist us, as determined by us.</p>
                            <p className='font-weight'>
                                4. Your Choices.
                            </p>
                            <p>(a) We make every effort to prevent undesired disclosure of Content or Personal Data. However, we are not responsible for how others may use Content or Personal Data that is disclosed by you to Users, third parties using the Services, or that you elect to share through any setting, selection or choice in your Profile Dashboard or Profile Settings.</p>
                            <p>(b) The Services may allow you to share Content on Social Media Profiles. If you use such functionality of the Services, then you should use caution when determining to whom you want to make Content available. If you choose to Post Content on third-party Social Media Profiles, then, depending on the privacy settings of your Social Media Profiles, it is possible that persons in addition to those to whom you intended to view that Content could have access to that information. Accordingly, you should use caution when sharing Content via third-party Social Media Profiles and you should carefully review the privacy practices of such Social Media Profiles.</p>
                            <p>(c) If you remove information, Personal Data, or Content that you Post to the Services, copies may remain viewable in cached and archived pages of the Services, or if other Users or third parties copied or saved that information.</p>
                            <p>(d) You may opt out of targeted advertisements from some third-party companies by visiting the Network Advertising Initiative or Digital Advertising Alliance Consumer Choice Page, which provide simple ways to opt out of ad targeting from participating third-party companies. When you opt out, your selection will be stored in a cookie that is specific to your Device or computer and the web browser you are using. The opt out cookie has an expiration date of five years. If you delete the cookies on your computer or Device, you will need to opt out again.</p>
                            <p><span className='font-weight'>5. Security of Your Personal Information.</span> We exercise care and prudence in protecting the security of Personal Data provided to us. We carefully protect your data from loss, misuse, unauthorized access or disclosure, alteration, or destruction. Specifically, our Payment Processor uses Secured Socket Layer (‘SSL’) encryption when collecting, storing, or transferring sensitive data. Personal Data is stored in password-controlled servers with limited access. However, you have a significant role in Profile security. Someone may see or edit your Personal Data if that person gains access to your username and password, so do not share these with others. WE TAKE THESE PRECAUTIONS IN AN EFFORT TO PROTECT YOUR INFORMATION AGAINST SECURITY BREACHES. HOWEVER, THIS IS NOT A GUARANTEE THAT SUCH INFORMATION MAY NOT BE ACCESSED, DISCLOSED, ALTERED, OR DESTROYED BY BREACH OF SUCH FIREWALLS AND SECURE SERVER SOFTWARE. BY USING THE WEBSITE, YOU ACKNOWLEDGE THAT YOU UNDERSTAND AND AGREE TO ASSUME THESE RISKS.</p>
                            <p><span className='font-weight'>6. Your Profile.</span> Users may review and update Personal Data by logging into their Profile. If you close your Profile, we have no obligation to retain your information, and may delete any or all your Profile information without liability. However, we may retain Content related to you for any reason we determine unless you choose otherwise. We may also retain and use Content Posted by you if necessary to provide Services to other Users. We disclaim any liability in relation to the deletion or retention (subject to the terms of this Policy) of Content or any obligation not to delete the Content.</p>
                            <p className='font-weight'>7. Cookies, Tracking Technology, and Do Not Track Requests.</p>
                            <p>(a) We and other third parties with whom we may partner may use cookies, clear GIFs and .pngs (also known as ‘web beacons’), local shared objects (sometimes called ‘flash cookies’), or similar technology to help personalize the Services. A cookie is a text file that is placed on your computer or other device by a server. Cookies cannot be used to run programs or deliver viruses to your computer or other device. Cookies are uniquely assigned to you and can only be read by the server that issued the cookie to you. A web beacon is typically a transparent .gif or .pngs graphic image (usually 1 pixel by 1 pixel in size) that is used in conjunction with the Services, which allows us or third parties with whom we may partner to measure the actions of Users who interact with the portion of the Services that contain the web beacons. We and other third parties use web beacons to measure traffic and related browsing behavior, and to improve your experience when using the Services. We and other third parties may also use customized links or other similar technologies to track hyperlinks that you click and associate that information with your Personal Data in order to provide you with more focused communications. You have the ability to accept or decline cookies and web beacons may be unusable if you elect to reject cookies. Most web browsers automatically accept cookies, but you can usually modify the settings to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of the Services.</p>
                            <p>(b) ‘Do Not Track. We will do our best to honor a ‘Do Not Track’ request but shall have no obligation to do so. Further, you understand and agree that we shall not be liable for, and you expressly release, indemnify, hold harmless, and defend us from any claims you may have related to our inability to honor a ‘Do Not Track’ request.</p>
                            <p><span className='font-weight'>8. Compliance with the Children’s Online Privacy Protection Act.</span> We recognize the need to provide further privacy protections with respect to Personal Data we may collect from Children who use our Services. For that reason, we make every effort to comply with the regulations of the Children’s Online Privacy Protection Act of 1998 (at 15 USC § 6501–6506). We never collect or maintain Personal Data through the Services from those we actually know are under thirteen (13), and no part of the Services are structured to attract anyone under thirteen (13). We expressly disclaim, and you expressly release us from, any and all liability whatsoever for any controversies, claims, suits, injuries, harm, loss, penalties, damages, arising from and/or in any way related to any misrepresentations regarding the age of any User. We reserve the right to suspend and/or terminate with or without notice the Profile of User who we believe has provided false information when registering for and/or using the Services and each User agrees to make no further use of the Services after termination and/or during suspension.</p>
                            <p><span className='font-weight'>9. Linked Sites.</span> The Services and/or third parties may provide links to Linked Sites and data provided by third parties. However, we are not responsible for the privacy practices employed by Linked Sites, nor are we responsible for the information or materials that third-party data contains. This Policy applies solely to information collected by us through the Services; thus, when you use a link to go from the Services to a Linked Site, this Policy is no longer in effect. We encourage Users to read the privacy policies of Linked Sites before proceeding to use them. When you conduct e-commerce with a Linked Site, certain Personal Data may be collected by the Linked Site and made available to us.</p>
                            <p className='font-weight'>10.  In the Event of Sale or Bankruptcy</p>
                            <p>The ownership of the site, Gameofgames.com or the company, Game of Games may change at some point in the future. Should that occur, we want this site and the company to be able to maintain a relationship with you. In the event of a sale, merger, public offering, conversion of the company entity into a different business entity, bankruptcy or other change in control of Game of Games, your information may be shared with the person or business that owns or controls this site or the company. Opting out of receiving information from third parties will not affect our right to transfer your information to a new owner, but your choices will continue to be respected regarding the use of your information.</p>
                            <p className='font-weight'>11.  GDPR and European Individuals</p>
                            <p>As described in this privacy statement, we will not process your information without a lawful basis to do so.  We will process your user information with your legal consent (when you voluntarily provide information or opt in) or on the basis of contract law (when you enter into a transaction with us), or when we have a legal obligation to do so.  As described herein, we may also process certain user information on the basis of the following legitimate interests, provided that such interests are not overridden by your privacy rights and interests: delivering content, and further developments and improvements to the Site, learning from analyzing traffic to better serve all Site users, to analyze the likes and dislikes of our users, and to help us to provide a more stable, consistent, and secure user experience.  If you have any questions regarding this please contact us.</p>
                            <p className='font-weight'>12.  California Consumer Privacy Act (CCPA)</p>
                            <p className='font-weight'>California residents have the right to:</p>
                            <p><span className='font-weight'>(a)</span> a specific list of the precise categories of information we are collecting, how we are using it and what the purpose of this information is;</p>
                            <p><span className='font-weight'>(b)</span> Links on the Website to opt-out of all data collection or have their data removed;</p>
                            <p><span className='font-weight'>(c)</span> Access to a link through the account profile management that selects:</p>
                            <p>&nbsp;&nbsp;&nbsp;&nbsp;“Do Not Sell My Personal Information” and link to a page to select such preferences;</p>
                            <p><span className='font-weight'>(d)</span> Information explaining at least two methods of contacting you in order to update, change, remove or transfer personal information;</p>
                            <p><span className='font-weight'>(e)</span>  notification when the Privacy Policy has been updated;</p>
                            <p><span className='font-weight'>(f)</span> equal treatment for Californian residents by us, despite the additional protections afforded to California residents under the CCPA; and</p>
                            <p><span className='font-weight'>(g)</span> right to have this list of your rights as Users that residents of the State of California residents.</p>
                            <p><span className='font-weight'>13. Advertisement Revenue.</span> The Services may display advertisements operated by us, our Affiliates, and/or third parties. Some of the advertisements we display are targeted to you based on your online behavior and your click habits and we may receive compensation based on your clicks.</p>
                            <p><span className='font-weight'>14. Changes to our Policy; Miscellaneous.</span> We reserve the right to change this Policy, our Terms of Service, and our other Policies at any time. We will notify you about changes to this Policy by placing the updated Policy on the Services. You agree that your use of the Services after such notification will constitute acceptance by you of such changes to our Policy. This Policy is and any disputes in connection with this Policy are subject to our Terms of Service and our other Policies which are each hereby incorporated herein by reference. In the event of any conflict between the provisions of this Policy and our Terms of Service, our Terms of Service shall control.</p>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
        </>
    )
}

export default PrivacyPolicy